In [1]:
#! pip install joblib

     |████████████████████████████████| 306 kB 252 kB/s eta 0:00:01


In [6]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np
import pandas as pd
plt.style.use("fivethirtyeight")

In [88]:
class Perceptron:
    def __init__(self,eta: float=None,epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4
        self.eta = eta # learning rate
        self.epochs = epochs # iterations
    def _z_outcome(self,inputs,weights):
        return np.dot(inputs,weights)
    def activation_function(self,z):
        return np.where(z>0, 1,0)
    def fit(self,X,y):
        self.X = X
        self.y = y 
        X_with_bias = np.c_[self.X,-np.ones((len(self.X),1))]
        print(f"X with bias: \n{X_with_bias}")
        
        for epoch in range(self.epochs):
            print("--"*10)
            print(f"for epoch>>{epoch +1}")
            print("--"*10)
            
            z = self._z_outcome(X_with_bias,self.weights)
            y_hat = self.activation_function(z)
            print(f"predicted value after forward pass:\n{y_hat}")
            self.error = self.y - y_hat
            print(f"error: \n{self.error}")
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T,self.error)
            print(f"updated weights after epochs:{epoch + 1}/{self.epochs}: \n{self.weights}")
            print(f"##"*10)
    def predict(self,X):
        X_with_bias = np.c_[X,-np.ones((len(self.X),1))]
        z = self._z_outcome(X_with_bias,self.weights)
        return self.activation_function(z)

In [89]:
OR  = {
    "x1":[0,0,1,1],
    "x2":[0,1,0,1],
    "y":[0,1,1,1]
}

df_or = pd.DataFrame(OR)

In [90]:
df_or

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [91]:
def prepare_data(df,target_col="y"):
    X = df.drop(target_col,axis=1)
    y = df[target_col]
    return X,y

In [92]:
X,y = prepare_data(df_or)
ETA = 0.1
EPOCHS = 10

model_or = Perceptron(eta=ETA,epochs=EPOCHS)

In [93]:
model_or.fit(X,y)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch>>1
--------------------
predicted value after forward pass:
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epochs:1/10: 
[ 2.34296122e-05 -3.36078276e-06  9.99534646e-02]
####################
--------------------
for epoch>>2
--------------------
predicted value after forward pass:
[0 0 0 0]
error: 
0    0
1    1
2    1
3    1
Name: y, dtype: int64
updated weights after epochs:2/10: 
[ 0.20002343  0.19999664 -0.20004654]
####################
--------------------
for epoch>>3
--------------------
predicted value after forward pass:
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epochs:3/10: 
[ 0.20002343  0.19999664 -0.10004654]
####################
--------------------
for epoch>>4
--------------------
predicted value after forward pass:
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype

In [78]:
model_or.predict(X)

array([0, 1, 1, 1])

In [28]:
type(X)

pandas.core.frame.DataFrame